[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'self'; script-src 'unsafe-inline'; connect-src 'self'; img-src 'self'; base-uri 'self'; object-src 'self';  "
